### ISSUE TITLE
ERROR: LoadError: UndefVarError: TOMLCache not defined

### ISSUE THREAD

**Issue by leferrad** [JuliaPackaging/Preferences.jl#13]
I'm using Julia 1.5.2. When I install and use this library, I got an error about TOMLCache. Here is the stacktrace:
```
(@v1.5) pkg> add Preferences
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
[ Warning: julia version requirement for project not satisfied
julia version requirement for package `Example [227d26fe]` not satisfied
  Installed Preferences ─ v1.2.1
Updating `~/work/Example/Project.toml`
  [21216c6a] + Preferences v1.2.1
Updating `~/work/Example/Manifest.toml`
  [21216c6a] + Preferences v1.2.1
  [8f1865be] ↑ ZeroMQ_jll v4.3.2+5 ⇒ v4.3.2+6
  [a9144af2] + libsodium_jll v1.0.18+1

julia> using Preferences
[ Info: Precompiling Preferences [21216c6a-2e73-6563-6e65-726566657250]
ERROR: LoadError: UndefVarError: TOMLCache not defined
```

**Comment by giordano** [comment]
Yeah, the package can't be used with Julia v1.5, only v1.6+.  It can be installed to make it possible depend on this library independently from the version of Julia (it's useful in certain situations), but it can't be used

**Comment by Byrth** [comment]
That status of "it can exist as a dependency but cannot be loaded" seems to break PackageCompiler.jl because it automatically uses `import <packagename>` for all packages here:
https://github.com/JuliaLang/PackageCompiler.jl/blob/e258108fe62a1917bf2a53819afdc4385e2a09df/src/PackageCompiler.jl#L192

I am trying to work around it for my sysimage.
